INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('3D9CH7PUE90ELMH59F0BUFKLDC','Nasdaq:ARST','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6KQF8DHJ05IBVQBN6CTK9FBO24','OTC:CGIX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('J82AS9M4VVHTNDLE1A83HRLGF','NASDAQ: SDBT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6E1029M796S89PEFLE31I4Q273','NYSE:SAI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('11MG90EIKTS7GBUBEAOKEQJADD','NASDAQ:MSFT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('23TKMLI5KON6HSBCTR6LOCJG2H','NASDAQ:NTES','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7B4TUJQV6BP41JGT52PSL19FGJ','NYSE:GIB','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3CFD1FPUQOFD7VN0NHAFFPKMB9','NASDAQ:CSCO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('JOHNQR425DD7G9JS9B9FPMSSH','NASDAQ:BSFT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('72SPEVSLSMT144ETN3G3F6619P','NASDAQ:CLVS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('4D4CJG2PIQ7NF2D2IDMJVHB4T3','OTC:SBOTF','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5O938TF7UREUJ7M0D378MHUJIK','TSXV: LEC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1N2SDC08G0I18122P6EDRQ8THE','NASDAQ:TNGN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('412JGM3ST83C7AB4NEG0RQAONL','NYSE:CAJ','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4AOEILADI7T3NL69KDEDDP7C2H','NASDAQ:FMI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5LGLUVK186683PVHHRIEFSO3C2','NASDAQ:HPOL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1MSOU80U9A93V4I70MCQHBLDFT','NASDAQ:UBNT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4AG3S4FHLDVMD76UP0TGVTN01Q','SFSF','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2588PG07BT6CUO6D93QCKHEN8H','PRSS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1UGTS9STHMR5GPN6HUEG2CPGU1','NASDAQ:ANAC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('4FO3V1ESD6TMB2Q67FNS0TJNA8','RAX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('56QCLE90QFJB0UAOPMK18KG9UD','TIVO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('585SBQBE5PHH1FJU1LFES9CVAU','NASDAQ:MELI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('687B5VDELQE6J8N7DFTAL9AU2Q','NASDAQ:CA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('73G6R5K5QBH9EJ2RV01PU8A8JL','NYSE:YUME','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('29NE66GHGQRMKJ2Q110K6NEQUG','NASDAQ:TQNT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2DJ0RH5RA72D4II2D87MF7CSH8','NASDAQ:MACK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2O6RLVT89BBLAVD4QUOEUTN64C','NASDAQ:NKTR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4VPJOJ140RHUHT3BT2NVMAE481','NYSE:JNJ','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1PGHQSGEQ70TF8H5T0GFKNTEFG','3632','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('31IL302OKFOR08NDSQ27B2RIJL','NASDAQ:CLWR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1NLU2ON8E0QLNTI3QGR56BKRU','NASDAQ:TSRO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('9KEG876GJTFTGKOI4L7IH2RU4','VRAZ','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3IDH759HFJ65B6K2KQNCV57QQ8','RALY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('30ECAO0L0AEIG6PU1S3ASGOQCE','NYSE : ALEX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('349APDV6GMHVGQ5LG6SVJ3SL43','NYSE:BURL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('DEMR4JHV18T8F59DBKEJT9Q6L','DGI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('18JRNH35CI0LA7E5L9S0TKAM3R','NASDAQ:BRCD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('75B4SSB3KDI9J899T4LBE0P9J5','HKSE:1688.HK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('BFFC41O8AR0GAHEO4FST4VUHS','NASDAQ:INFY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('DFHVTAC6SFREQFNNNSUVQS22B','NASDAQ:TBNK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('PA8NR4EB3RK2MVKJ822LP4M1D','NASDAQ:CDW','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('FKQ4LOKFDHEJESPBVEG5QGP9C','NYSE:YELP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2V3BSULNJL8K1O9995CL95NVD8','NASDAQ:BRCM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3RG2K669JNIVREK9NHTA9L481H','OTC:MPSYY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7IRCS46NPNOK1DV6MCKCU9T1PB','KITD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('ISNLBO9CJRFUQC9T9589TRUIA','NASDAQ:INFA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('VODHTRD99AQT355AVAMJCD08','NASDAQ:ONTX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4UEVE0MT7N9P4131A444KSO149','NYSE:EVHC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('244FGBSM98DPVK20UT1NR82OEB','NASDAQ:ONTY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('42TVTE4OPSJCLEDOESU275QQ87','NASDAQ:SRPT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2NHKIAMAMKR4OUJTK6N70IALF','NASDAQ:ITRI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6NMDMOO34U646RBBT07DM4O9MG','NYSE: AMD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6M8J4EARNM8FISO8T8IUKG1R8J','078340','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('224LVV2QU0RFTBNTT86C0M3RAJ','NASDAQ:CTCT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('34PDM37TA4O7V2JUOL2HIIDFHM','ARAY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2HT8UCHNLBK1RRFKO52IUJ576S','NASDAQ:BV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1R25EP49ESDED7IQ9NOTA6DLVE','NASDAQ:SPLK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('10TMV5UOR6IAA1FE9T1S2LBI1Q','NYSE:TDY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('44TDUHM30RAOVBT3DCSI0067KA','NYSE:FIO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5DP5HQEVPF11MC7RB08R50VVEK','NYSE:NYX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5BHQ9K05T0KDV3NPT879ENNS6O','NYSE:HLT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4VD82K2LR8CDJUO5MTAVH6GVF3','TRIP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7TETRESCLUSE5PDSJ139E2G4VC','NASDAQ:SCTY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6COA0FDL45JQ0DN25IJR7IB515','XOXO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('KC6KN76JFEUSQ9ANVIFQVB56V','NYSE:VMEM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6KQJGNR0H24J0IEBCDDEEA19IM','NASDAQ:INGN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5KIQV517QDQT6BP2SIIV9MRDBB','NYSE:TDC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7B4JPF706EBTBKSGA3IB3G2893','NYSE:VCRA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6289IGNDKT3CGMVO212E0IVBDF','NASDAQ:ENTA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('57KKT23G58I44076O9QR5UIJQP','NYSE:EFX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7KH2346UM8792KS4KTIJQPJNI8','TNAV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1OGMANU8BGJ80782R8MLVD45B0','JTV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3H9GH3L2VC2M447S6866G29GID','NASDAQ:GOOG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3D4D5HI5PF7ONTHV4JIRUBGMO3','NASDAQ:SAPE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3E4I9RFCHE8TS5PUDRTJKDBOLD','DHX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('11AGTPNH3265NBKTQTDLQQV55E','SCOR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6Q74EIVONQ1BJFC5L2VA72BUIL','NYSE:SAP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('F0OPD0VUMEDCPBU76QTV44K0','NYSE:WIT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2SM6GOOAQOOGU547UD6EQTK5BE','NASDAQ:KBIO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('3L5B7PNHC42L44KSL4MQHV6M2Q','NASDAQ:TRNX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('597JAA4JR56AH00HO975HOEVSQ','NYSE:CBE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2ITPHNMGLF9FT0ROG2RA9NI0V5','QPON','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5CTONRCS16EOAH3LBQUKAQG13P','ENOC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1IU57MIU1DTGN6TD3HHQ04BDD9','NASDAQ:BIRT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5D8OC3LE5NF750C9PCE97FV4M0','NYSE:MRIN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6GLGK2CQOF03UBU0T5Q4S7OI9I','NYSE:ARMK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2VKOSP96NRJIOLH3I4CHPRFRA0','NASDAQ:AMBA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4C2OQELTPSVH9IT6RG0IGCM32A','NASDAQ:PTCT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('27PMEESE9E5C82VQIS396PHOQ5','NASDAQ:SSYS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('489JIBMPEJ53MB0F2PGG4U5CB8','1254','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3O7IAMSFAUM2B863ISOFBODPJQ','OTC:FNJN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7NCUGJKR4AOAO5NQNUQ3IK1SQU','NASDAQ:FOXF','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('QK2CRQUBPEU3IENUDE41E8JUK','LYV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2BOUNS7DC5C578C89S4FLD1BNO','NYSE:XON','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1FDGJ3S4EH9CUIS1FV46R4PS5E','Nasdaq:XNCR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6M0NC0P38LUJJOCCL86TLLR5JP','NASDAQ:SPSC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2998LBQ666KH5VPA61P68SGMC0','NASDAQ:MBII','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1VSM06OT9OUGANAJ60V4Q831AV','NYSE:GME','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3FB99VK1L7MHNG2UJUMOL11VSU','NASDAQ:AERI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5BOGV5VJDMHOK411EFDSDJ90QE','LVLT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6RD9AQ7I5EP8IQ0R7L25599AD1','MKTG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4KE8EKKMDDVN29A48G2DBGPF4P','NASDAQ:AMAT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4G1TGBK53IC9QKM4QBEI9DMJH','NASDAQ: OGXI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('65HMBILA3S4A0A485LUDLQ0LHD','NASDAQ:CHRM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4UB02JGI6QPD1F2FE5GJCJIP1I','NYSE:TFX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1EDG1C3RB9QGTMPC3M3DGVJ4RC','NYSE:HON','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2AR7Q05AQAMMJ6683TU1EKF79M','NYSE:QIHU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5B6Q5B77AKI4L1CGEPLVHJUNOF','NYSE:LOCK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6KFQV59J2GGB0A53SJRT6H8L3D','NYSE: SNY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('2TOLI9BN9A8IVMMUTFRIG3V9L','Velt','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('27DCE8SDVDF81RRKPA177CUURQ','NASDAQ:GSM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3ALKFNROHOFE6RFT41KFS92KKT','NASDAQ:ARMH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1SP9PVGJI2KVN8MKMTKM23FATF','NASDAQ:VOD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('H649BRHSNUA2VHPFBFIRVVSQQ','OXFD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5BR23M5UFI46G5MT1OFDOFQUTS','NYSE:GLW','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2RUSLJN8O4L9AP24LHR6BCOLP7','NASDAQ:PEGI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('251815IU948PFF4SKMFM103NGU','RMGN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2N5NQ9VFQ4PRH9PGTI56IOSKCM','NASDAQ:CSII','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('RBR1J48B7FALICKNG1FMCFRRH','NASDAQ:EBAY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('2DC7C5KGFQOISC5LKLED6JLSSA','NASDAQ:ORCL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('788UMG0STEG3MDEJ23TC5N3TUC','CTCH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('53I9RNRAC5JLGHERBMIKLC1K9H','NASDAQ:TIBX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5N5C5C8FPQHVGA77FPT3K1I2QD','NASDAQ:RLOC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6OLHC3DDJURVUNCAS5TFVQ0M0A','NYSE:BBY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('608BG157ISLJT77CTT78CECP8T','NYSE:EVGN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3R6JIQR39E4K7FUG1NK1P6FCU8','ELT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('HILQ0689K0G362VEUA1BJM74H','CDCS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3FIO6JUFNRD1QBDAHE6JAJ83FM','NASDAQ:RVBD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3RFRPUPT7NSAMIQ8G155LAAU09','NASDAQ:ACOM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('78LKPQ5IK5A489TM61T60REN1','NYSE:CACI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('EFOJ71NG6LT530JE95OSF27D6','QLIK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5HL083D2F2EUL2FJRALNPRL41S','NASDAQ:HWAY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('F1CGPK9QFEOU2GFE1KJ0NDH0V','Nasdaq:GTAT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4J664VSU2U1IICTUQVUSQCOVDC','OTC:LJPC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('9VC7SIJOP6J7GGKQV5M5TNVF8','NYSE:DIS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4RAN78HTTKKDC95FIOCQ9SB0K4','NASDAQ:VNDA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4VP37GM7RL8PCAB606SHVQOAGE','NASDAQ:CGNX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5NK9GBR7OGLVV317SLQE0GSPQ4','NYSE:ACT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5PBGUL1UI78GOMDTUJARLER006','EM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('20FNID6I3JGD8FRQQSQT7QHCGS','NASDAQ:YHOO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('ALA293LFUB602P1R2VJ20D45J','JP:2121','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('55LML26HKVD1KDHGN1032CID5M','FORR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4IE4JUOGF15C9FRM7059V0JDI8','Nasdaq:BDSI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3EI5CVVUR4IES24D10GRTI5R6C','TYO:2193','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('46KKBO2EF1ILU039INFO5DO8MT','NYSE:PAL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('38AOGN8EGV4BOP2TIAFLP1QQ0I','NYSE:CHA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3G1BGPV7CRU2DOAOBDNST40SQG','NASDAQ:FB','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4LO1QJBI1C8T632S4LSJ9N9IC9','NASDAQ:EPZM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('536NI0E04CE2HME04FPI8IKIQ4','NYSE:THS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('2JFI3P67N8T10H8137B5M4B1LV','NASDAQ:MCHP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('78ASK49H3DNAP25K56GJMGG41C','EBR:ABLX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('76KBDKOA38VJJV3A2CGE6A2JTU','NYSE:LYV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('DTRFRD5N8FEV1G8QN7A4CVRK','NASDAQ:MCHX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('G8NQ64RP2EE80M3GFRV3LB7DH','NYSE:ACN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2EM1LGU5SRUI3BNJH2QA3A3BV','NYSE:DHR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3OTGL1SSJDU8C3UMISC6NJSUQ3','NASDAQ:NVLS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7Q6IK0HKUGP9GDVVU2J7HJKRP5','NASDAQ:PDCE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('77D6VLCTNE2DLI0GQ2BTMJO89Q','CYOU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('FUM1O154EEH1RJTF1JEUPGEMI','NASDAQ:OTEX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('62VQGQQHAJPSRDLUOS7JL953S5','NYSE:ABT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('18DMIGB4MUJSLORK7FPQSSHV5N','OTC:TTNP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('V192TVT415KUG5OP28OSJN0PV','OTC:MLSS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('93B2G46GKLGM5900KS2I10OL','NYSE:VNCE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2P1PCAF1IUF6MSRQUNTDF5S4TG','NASDAQ:SATS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3GGLA0JOTS4CIMI8FJOKCIOK18','OTC:CMI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('148CSCGC8P0KPH1LGG49A4K7GF','INFN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1JLP23ELGDJ919L9139L4CJ4U5','UNH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('29S9712J2T11TDM7ER07LP40A','NYSE:WMT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('QAOF9NLAS5DEH03C42F17FB9J','NYSE: CNC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('51NC24BN6BU5NKTR2RLRN0DMDU','NYSE:ABB','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('510OB47KNUSRGNC0MFGI8B5ITL','OTC:LSCG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('62IDGNMF1T9GU04HVMUVJ5D27O','NYSE:IRM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6DILPJGIC9GNIJGT9UL3873O7P','GA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4FDR91BTAGE3MC2NUIC36QEHHP','NASDAQ:QNST','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4CBPLCM6L38863FOB7GABLAEG','NYSE:HPQ','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('57RVG9I4OF1SQCA3PF09VV37TG','SZ002315','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7G655NP3UODVKBG25KUBJ3BBLM','NYSE:CFN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4DDRMH8I64R60HIJ3OB9ILRMFD','NASDAQ:NFLX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4PKHNSJ39P9GKC6OUPU8HL9UN0','NASDAQ:KLAC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('6CCS83QS6LMKBDLIQQ1BFD2BS2','NASDAQ:NXPI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4H2LVMKV8UD5VE0C7HPHOGMM65','NASDAQ:VSTM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7K3B0BMA92DUSLNFL9975LQ2KK','NYSE:BGS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('185MDPO0NGI4OHN4LHEE4IATC0','NASDAQ:FFIV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('76N16OQ9B13U7NJ2DKMN30FA4Q','NYSE:BX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('19RR5L98U8DII6JMT8UKED8F98','NASDAQ: CYBX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5TDSEN8FBOU3CVI65QUCQ51HG8','NASDAQ:RMTI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4P3KS0KKVL7TGRIH1KD2L8GS2J','NYSE:NVGS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('711VKJG0D4V98QBPK6T6BK015K','LON:GLEN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('8DL7QCT8ACEJHJ6P462U93DJH','NYSE:XRX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5BSS3R81JI6UOIFMO9EOJROF09','TOM2.AS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('U99BC8MP135BHGN0P07R6BM1V','NYSE:KYO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1CBIM15KIRUTI5B1CLNOKBAD3G','NASDAQ:BMC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('29HJ930CV5OE6LEOOP1S8NQ84Q','NASDAQ:DAEG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6DU27OFQR5PFDLR3GTS5A7151O','NASDAQ:MERU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2AQC0FPPRPE28OF7C8H216CBU9','NASDAQ:CDNS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('56F8VSAAR0H9O518JB6VSJHD31','NASDAQ:BCOR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3PEVMQSBC0HNNSGQ68JT582SLC','NASDAQ:DCIN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('35EFGIS2F4L3BUV338Q2L4UE3F','NYSE:EMR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('RNHL8P3QOD2VUJUJAOK7Q92RQ','NYSE:LITB','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5AISA0B8RA7MBCDSK1LHG4MUNM','NYSE:UMC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('17DFRU1RD7EGHF8TILE1CMH9I2','NYSE:TKC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5BODJ1HE2R780KB0L15A2UP4EK','NASDAQ:EXPE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('S93VU0RTT6S9AB97Q7B697H21','NASDAQ:BCOV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('75CE0BOC4P190QVGDB033SPGIL','NYSE:RATE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('62O0JTHHH500O02HE30GQKDL66','EPS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('62EQF7CJP29SDBIL9TC4NCTBGF','NASDAQ:SNTS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2P0S82UCU0FTTQUSG9HPM40ODE','NASDAQ:VRSN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('28MFDQNQ6MPBC248TN7PPCKMTU','SOLR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3MA6KQUHO5VIJ9QCAJ79PMSLPB','NASDAQ:MSPD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('275A0K70GJINLJQNTP1HVF0GRN','NYSE:ONVO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('789L1DCG1DGBNIE3QL4PASKRSF','NASDAQ:AMGN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('40G4SQTOJ32HBMLH9Q5U2GS9IR','NASDAQ:KYAK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('45C5JSLPGV43NEDMHARKSK56HJ','GRVY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2J00VKML4P5VQ7TTNG58USET0U','NYSE:EMC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2JFQ5LJ97OQQGF8V99OHUMRM5S','NYSE:WPT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1FH9P3R608323AE7IOHS4B7EA9','NASDAQ;CTRL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('63N2E079C7US76PMIQKUQD6M6K','NYSE:VMW','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('U2L12BOQM43AS4UHIDQVIDHT9','NASDAQ:DVOX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('66N216US9GN5I6PMK0CFDPQ6CV','NYSE:PAR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('6CCS29RH96KBL20HIHLLGDAK9E','NASDAQ:NEPT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2G4PP72Q809QUP85CLQ12C4D2G','NYSE:PAY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4OLRO27PN107HCDLSNB8CVFDTG','NYSE:AR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4D2N26OJ0J0VMR393SQ5KI032J','OTC:ALQA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1FS8FETEVDMSGE18KTMKPUPNUT','NASDAQ:ILMN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5S6VNVMROKMKDIMP78MQKKI3FE','OTCMKTS:CRWG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3L279TO6M23TCGJ24NN8G1SERH','OTC:COPY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1C8A6FKK7KHPPTBFMLPK1Q2NJ9','NYSE: CLH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('63P4GHFI725F00C19U182L9NC1','NASDAQ:ZGNX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('48B25QPS6QQTK71LVDSPT0RMUV','IL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5TI96U9B079GJL0OQBIJCRQT0D','NYSE:NYLD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('25013GR5LQK4B770UE1GPKU0L9','NYSE:ATHL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('29F5DRTAGQPATDU5SQ46QLAH6O','OTCBB:SGLB','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('PFELVKH3TBVJP87J8BFRV2TIG','NASDAQ:LDRH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5U2ID9I7GPDMCOSKR86RKK15P9','BKS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3SEGT2VS0PNP9CKC08EILPMON8','NASDAQ:QPACU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('24IUGR55PHO91FI4D3GQ52C36','NASDAQ:IRWD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('FSUTH8MM6GRNIGHEUFTG0UI62','NASDAQ:BRKR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6729KK493GCEUJFQSDJS9KPJ3Q','NASDAQ:ZU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2SJ7JNSI52B601V2V76RTA6R3','NYSE:RHT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5032HCFFBRABR00QBKAOS35C94','NYSE:GSK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('15CLQRFNDQGDBF4QVBSU0UBLF9','NASDAQ:CHTP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1MFAFFNV7MIISBGCQ2N9QD35KP','QXT.L','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1SC4A7NMKD1PQHNQO6SQ8OMGV8','NASDAQ:XGTI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('LFD26N8EKE3ICNLIEQNJBG2MI','Nasdaq: SQI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('41A75I48OJRLHN9IE6NOAMKRU6','NASDAQ:LOGM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('323Q0F8EHB045SANGC95DUBMB4','NASDAQ:SNPS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3ITPP9EELJ7HO4T4Q0M497T0N5','NASDAQ:ENZY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5V6H0CMGN69U6NB2LLO7191KED','OTC:ATCH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6VFP0QJBU8R7N9TRI80LNRUTK6','AIM:AND','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('271ERQ1PUQGQRRID7946N6DDF8','NYSE:POST','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('PVTF4GUPLOJHB00U4GI8UI9KE','NYSE:TRMR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7H8JN7850VIF48UJJUGK7AE322','NYSE:DLX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1O8VB4LG2HDQHPDE87605CU1L8','NASDAQ:OREX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7794MSPN1V95O0ITKKCKPDIKG2','NASDAQ:TSYS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('786H3BD97JUGOOGPBEP09OOVVL','PINK:CRXLY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('GOSMNOP9K25M94J8CV9J89IVI','NASDAQ:ANGI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6QTCOMG35TUG8A7A0H9EKM5D4M','NASDAQ:AKAM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('24C3N79BH6CKT4B4NI9S3129V7','TSX:ISV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('QSEIPC4SHEK2S2H38OCH2ATRL','NYSE Amex: LOV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('EJG3LNN8G160DNFL7QB9PMNS5','ASX:MSB','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3O63O8IVMCLBJ0Q5C5MCQIE8R1','NYSE:NLSN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7AIUF0UDR4S8J5NIAP7MJ09RCL','LOCM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('13E0RS2NUN1HOD1U5SJTDTPEPD','NASDAQ:ADSK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1OBU601TP9R5PRG68OSJUNBFLF','NASDAQ:DELL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1QFBOVFBRUN3RH13OPPQ9EG9DI','NASDAQ:NDLS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('44QCPDS80TKMRKTOF2NOSAC2HU','DSCM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5R0A2VG87GHG4UTUDL7IN9ITLE','NASDAQ:HOTR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3INDBDM7Q7KPPGFS12G5ELPHG4','BFRM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1HG01GDIBGCAIAC62OG7HI0EO0','HKG:2468','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('29IQC4J3SO423MAA89DL0AEQI5','NYSE:TWTR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('63VUA85NDVDAT2KHC44GCPPAOR','NASDAQ:FITB','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2FSHM5DAIVMLUE6REDSJKIRAHT','NASDAQ:PTLA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3CONTM7283L54B7794JFCADA1I','NASDAQ:DMAN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5A5AHHADS96AUBTCJCE2DB78HC','Nasdaq: TSRX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1HL4FGNNGC8U7JVETOH724HLLR','OTCBB:GCMI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('679GDD8JA626U925CQ5I7GDGQ3','OTC:WGBS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1GJU15PLV0AOJQF2OQS1ROODG9','NASDAQ:PDLI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7G4I74KFPHI2305SQQ8HBQH9DC','NYSE:NCR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('73HGCJ31QGVOPVR0AHFL5HMHIV','NASDAQ:WBSN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('7TOP8V267A9EB3KSUBFUM883','NYSE:FSL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4HF9GICIU9EQNMRVE5QMM9M89A','NASDAQ:YNDX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1D9N283P178LBDGPPG7N4SCGJR','NASDAQ:ADXS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('42GRJT8IRM2VTIVAK2U7OJT1V6','NASDAQ:HTBX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3TDTUFQHRAU2JUF5H63VIPRUGN','NYSE: XPO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2P60LS6J3Q5CK6T410DH8EI1HD','OTC:QRXPY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7MIFFB0K0B8OOGS3ETIMTGU583','NASDAQ:FISV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7UARS9HHLUPT5K4SNDKB3A7LAM','OTC: PLPM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('45SCEE7OC4MVU4EN3SASA0T1IV','BNG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('20AV1KLS4B1FLMMVPNO6MNS6S6','NASDAQ:AONE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('QD6CI9QUF5Q6ST7R3JMCG8JA3','NASDAQ:PAET','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2HKHD1N59NOOT54IDH870CNP7A','NASDAQ:TEAR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5OT3EJTQC06GMLGLSTUDK47ABI','NASDAQ:INTU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3UR4RE841QF688N6OE1TTBUG18','NYSE:DOX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4V2MDB7EMLRQFU03MU0PLPUNU7','NASDAQ:BOKF','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7KFH1C7AHNVILFL82ST889BUDR','NASDAQ:EBIX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3ISDO16HR4AJDQ9FD5BAC7CBBR','NYSE:BIOA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('23M661J1Q50TL40BTNIRBI08O0','NASDAQ:ALIM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('78GI0EJLH73BGH6SUKABCFDPCT','AIM: BGO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5BRHF77B96I3I8I0C6LA2TL90A','NASDAQ:TST','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('58UL55CFLVA64NHEIRHC66ATB8','NASDAQ:KPTI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('42PCF47B8O9QF3OAHKKU5F565V','NYSE:UPS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('48BFQJR1AQTMVO9QKPM8UDETLE','NASDAQ:NTSC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1AH3R4OS3ICN3NG638NKSMBJ5M','NYSE: FMS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3AJ10R264PBTNFQE674DOOAB39','NASDAQ:SYMM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6OQJGCAMDE3M1J2E1BLHHTCBM7','NASDAQ:EAGL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5GLTDGC7I4BU3SU7DNMA4V0L0U','OTC:GFOO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7TLRK4KIQ275JK6TACL4LGVOE8','NASDAQ:NSPH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('66KKJGU2R5NEBVB4URM7FEC3V','NASDAQ:SINA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('LN5QSMB2U5RK1O16AB4B2NFU4','NASDAQ:PKT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5Q581KUJCH7U3VS1UAQA9MHK8K','MG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4386GK05G2FNSGN07395K61J4D','NASDAQ:CTSH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('556PA53CK7R84NO9UQHHNV27FM','NASDAQ:DTV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('286Q1P0KV5HBHGI7VR304MPP07','NASDAQ:SYMC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4U6KVO7TVF80NBBF44K4F3KI0O','VRNG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('34SEGM8FK5ND1IJ9LHBJT785MK','NASDAQ:BBRY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5EC54FM032NM360BIP77CGH94G','OTC:ANPZ','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('56AIA1UE78GTKSPHTNVR1NTL3N','NYSE:TXTR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1CFEQ9RFOU44THU2QBRJ5663AS','TSG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3CS5UJVA60GQEVF40DO98M56KS','NYSE:MCK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('THPLQ280FLHOCIALE91M6SUMM','MLX:ASX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6GOL3AU92UQBOA2H6EBM8H1VV1','OTC BB:NNVCD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7EKO81TCNNHGTV58ALVRRHB91J','NASDAQ:AAPL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5FPOHC7E26TKE45HT15UNBBGLP','NASDAQ:CERN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('70KL6FBTFVIRASC6K7DA20KAFH','LSE:OXIG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3UIE4DOBV0LN1IC12EUBIS0R3C','OTCBB:SYTE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('76JT6Q722AQ3UHRQG1Q25QFBOV','NASDAQ:KONE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6A56523NQ7Q29KDN79HGHV0MBV','NASDAQ:ATVI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1OLI35AV4MG780C2M2PAFHR7GH','NYSE:COTY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1NJG95EO4HDSCTK7SGQIPAIMOG','NASDAQ:AUXL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('417PKFR2UOTFMVBJSCFD87PC38','NSDQ: GAME','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1M71R82GRK9Q9NL0TJJL6DIA0U','NASDAQ:PACT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7K6USQCO97126AVUME62RFB7ES','NYSE:SNI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7Q159R7E2BIU05KL5TT71TSC5S','NASDAQ:EVOK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6LMTL3OB1M3S2JTDJC1806V3F','NQ','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3EVP2IOL8G4B58FPF4VQNOM1H5','NASDAQ: PCYC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('9742HCS1MVNC9U4OPRC24JQF0','GKNT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('24RL50NNC2DA9F4MTLUI9RBK9I','NYSE:SSNI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1EJ139STBBQLR8JG4PNID6AT7E','NASDAQ:FSFR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4I7DLKOC2JTKPN8A1OLNUB3PVV','NASDAQ:INTC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('6CQ5PR2UTPSBJ2IUQK6T783L5','NASDAQ:HZNP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3AMLE0JD3V0T3Q1LM0UBEFR5BN','NASDAQ:PRFT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7NA49OBHC4A2MHVPTPGCQA82FQ','916:HK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('MA0B0DUHT3BG3HOIE0V05MSK','RPXC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3N6247QGP02059TI952SN97QOE','NASDAQ:BCSI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7OC3OBQFN94EF6MGA70NIRUL9','NASDAQ:ABTL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('569ET2T8NREMM40S3K0NU4T9VP','NASDAQ:OPEN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('73LK205RQPC02V2Q89EVK1IRA7','NYSE:CHGG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3QLSUMGLF1BTOSLNSQ35VKFFC1','NASDAQ:RNA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('A1RIUQAOGJSPO0LUI6LBSPVCO','NYSE:SNE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5BE5EGR775SOK2QC948JH013NI','OTCBB:APWR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('DTRQ0J3FJHF4K3G9R70EP0BMJ','NASDAQ:VRTX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('76TQKPC36IB3PS9Q4EL22AC46Q','CDON','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6M6MP0H8MKOUIODMQHBBV5U9E','NASDAQ:AWAY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6NC5KMOAA6GIT4RP6P941AIVVQ','NASDAQ:SGMO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2B48UQPEVNDEN800BDIRFM31BO','NASDAQ:WAVE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('ATF1UOVDSOPG2IR54T1F2U8EU','NASDAQ:TXN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1VGP6PBESTJI5U3BQOR1727Q29','NYSE:ROP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4FSLM40B4IUFGBU2T3R5PR9EDV','DIVX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6472T27746MRISRMBCAD7AHEHA','NASDAQ:ENDP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('20HTUFD82VQ70D5FFAHG1JGT95','NASDAQ:NSTG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6HUA020C12OD1HQMQ21K03NQ58','NYSE:MEP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7SP0QUCOUNU2MRQ6FF1JKKDLNO','NASDAQ:THLD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7R30BL9OT90PA5FA25P4AQGE88','ATTU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('NKHAIMVF0K811FRVN1LEBU8U1','NASDAQ:TZOO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3SK1K7DJGGM8JTC12O4NL56H7','NYSE:DATA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2GPLNQ49H8I87N5N4858SP5777','NASDAQ:EQIX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4PCI6VHDC2U4HHTH96NT3BB0BG','NASDAQ:OLBK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('64NUTO2TQ1RD452JULBVJF2TQU','ASX:BRW','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('50DNDP4RSISNFJR4PC8IF0OOU7','NYSE:BLOX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('7SO17UKNA912AA1V138FJFR6M9','OTCBB:XXII','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('TL9LCR7BHVC9POLP1RLNDMR1','OTC:ONCS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3G99NJ50EH9OVJCIVVN3K92OOA','NYSE:AMT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5R4ARPEB08KNULVFTTU0KIRV1L','PREC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('9SNU6RKA8MBCOHA2HBUK6GR8M','LON:KFX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('13QBLD0QEA1O1965UA6IJL41Q5','NASDAQ:COMM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4P4OH32LBT57HF0BE10K5AOL3J','OTC:SNWR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('54EHF13OBL3JK1J1B489KDCVDD','OTC:FRFHF','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7OBGCEHMBMGV9939QIKQ5KGOEC','NASDAQ:OCRX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2LA1DQ50DG2NM33S1SPCAHMAHK','PNG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('1FP6N8QNH3KD384LU88T4F0QLJ','NASDAQ:HSFT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('24E7H6R3P00OD4DQFB5041ERV','NASDAQ:SIRI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7HK09U4P40B96DJ49MPFC2SR37','NEPI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6J4DTLLOO734AA9KM07AM1GPQT','NYSE:AME','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('IHSJNC2M55PMVQBQJ574EI77G','NASDAQ:FSLR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4SMM46F4M2B9JQ2J1DMP5IVMFD','NASDAQ:FTNT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5F3FB8AGG1AMDH9HI946VTF1IC','NASDAQ:ZNGA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('9IIB6DPHSQMRKVILOL56CK81T','NASDAQ:BIDU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('37IBK16K735PSFH6Q9B3BTLJ10','OTC:TNTY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7FMR3RNQ7BE849HQJ07ADPSTPP','NASDAQ:SLXP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('6MQDBNBLDNVL6Q3DK9DC9Q9IH1','NYSE:IT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('46VOH3H1EJ3SOB9KP5GHJ4CMV6','KOSDAQ:063080','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3JGO30HKCMA63EL0KHJCOVSQ19','NYSE:ETN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('162SRJHNNDVCGPM2JAUIK78DG5','NASDAQ:LIFE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6N67BGR0ADLVF1RPQF86AKGSUM','NYSE:IM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4S44NNLF0NB8PMHGTCOB48FSLC','NYSE: VIT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1QJADCO37AH5EV7DD98MB4RJPT','NASDAQ:OMED','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5TUKF004PSQIO8BKUOSUT8C9Q8','NGX-4010','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('31QI5G6N6HFODIJNHNGPPOTG2G','OTCBB:CNSO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3KL6R3T2D1VLFUG2GBTKS23NBQ','NYSE:SPG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('51KECQ15PB58E6K6B640Q6MBEK','NYSE:ALU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5OLEMVBMH8K6JAE37OTO569AU0','NYSE:TRI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('32V976AGV67SEDLR3P2UGU6K6V','NYSE:RNG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2O2CLV2ETHHDMS4A6AJQPATSDS','NYSE:WDAY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5P11732BIESIREI5NM3M9VID2L','NYSE:IACG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('G1DI6SEM1U72231CTLEI4UQ1B','NYSE:SSP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5ISSCREMBJGO7S7FFKDUK6UE9T','GLUU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('35UK7O3C3EOU9QROF6D9D2C01L','NASDAQ:MNKD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1J5FK94JT0KLRS8TJ85SSHS31H','NYSE:PMT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2T11I78R8NGLVUHLKD80ITSFNL','NYSE:PANW','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('3T1PQV42N5DINT3REPLHVPFKQK','NYSE:MM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('295RN7D4E2SSDAR5LSJFN6R3MF','NYSE:APH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7AG83L91EJUSVRAH3IOTH1GRQJ','TPE:2498','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('55L8GC2IGGPETUUE47DKVM1RU7','NYSE:DVN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7027MB83MJ2Q0THRVLU9PV39BI','OTC:BARZ','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('54E3C4KFSOEQSHUQSCK2A82K2F','NYSE:AOL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5V360I4020L2M18TKOP1ELACQF','RSS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7RSU6JIMQ86Q989UNVM379QN0F','RST','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('624ED95FF2JS59V4BJ34UC5VG0','SMTP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('31JQ25DI1NRFSHACIQ1I1F4E8M','NASDAQ:BRSE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('6GADGDNI9RGH3DU240HJ7UUL00','NASDAQ:STX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2LECGM1BD378M7GR6ESJSJAC0E','NYSE:WUBA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3A99OFKMHKBBSJ875CDVF31S20','NYSE:CMLP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('64PC56NJSRIHTGSP3Q27LVLJNQ','RP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1IQINGU3BHE5U5DTQLKS0JUO4G','NASDAQ:ARWR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('251ML49G5HBQDNOTO4U58TB9PD','NYSE:VEEV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7RM3V2H5QI1JGNVINFS9B39EA7','CPIX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6M2I2F2COSFTJ0C7I3N1CLAP09','ECHO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4PPRTDBAHK6N669FOKRP32VGEU','NASDAQ:SWKS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2RGJ9E4Q713QJSG67DFKDTR8B3','NYSE:SUNE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('7U463BFHUFQADQURR1TC6H9V4Q','NASDAQ:GTIV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2J5BDCF9NKV2NN2MQQBMVO18QK','BIT:YOOX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5ULKG2189AIMOPQ3S7KAEKNPA6','NYSE:CRM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1F9T9GHUV2JDFSR826RE206606','NYSE:KT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2I8DJFTKS3FGKK66RPC093QMIJ','NASDAQ:STEM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2G7LV41MNIOAR9KON7VUA374PN','MDSO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3LQ5KLNFRHFN23TP2E13VH235F','NASDAQ:RRD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3JV6P755RINUA1BBDGN8E8I3FM','DRIV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('41BM7QLSSV46Q90AH04KCI7LKR','CSOD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4U8ENJ2LNOO1G0KHKO5GRS0HDN','NASDAQ:Z','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5O2Q3ADG20LH2NLEIB1H6BPVBA','NASDAQ:QSII','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2REE9RI7I30MOVQPNUP1GB6VHP','OTC:CLDS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1N5VFM19LJDTN0JK5MVRGG449V','OTCBB:GBSX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1J7SBB16ICBHFJJEQJD5UMSL3Q','NYSE:CVC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4GH3EM7N2G7ULMIID55MG0U0CG','SWI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('26G8TVD8PSMRNQIUCS81MIBGMM','NASDAQ:VOXX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4SFIEJJIG1P0FCSQOQ26J9R1D1','CAMH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('61L9UF2GV9VSJHNUQO729P6TRA','NASDAQ:ICGE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('A4IGU6K4RGOFS7BPMQAI282S8','NASDAQ:QCOM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7GP6IOGN74G78FO4A4A5715MUF','NYSE:GE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('7U0EDG3G3S4TLT1N312S1VAFSP','NASDAQ:CYDE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6LRC9P882C7L69GPPJ658DDHUJ','SLTD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4BEP45MHK1MGDAT2JB6R55ODM4','NYSE: FUEL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4QFPJLF98PTD2ATJJBST6VKGNS','NYSE:RENN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4CMUJM0EPQ6HDPTA55M56QCP82','NYSE:TWC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1GMER3M60HG0VFC725HN82T4OE','NASDAQ:MORN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('45E9U6O5N9H3BHVD5ICVEQC0Q','NASDAQ:HDS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3U3DNU6ICCS4UIURCQLM9HA4AG','NYSE:RSE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('57D1R3A800BGPQDOP1EN1LB2TS','NASDAQ:ANTH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5S35HAR0B8EH4P3L4MQDVMLJ6A','OTC:VSUL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('7882OECR1SMREPPRFHUPMDOMRH','NYSE:BSY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('CE2GUNK1EUP8TT3NOS15SU39E','OTC:SNTI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('79UVPK317TJGNQRKMV4D4B2OPR','NASDAQ:DRTX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1DVNJ7TD8AGM2S7D9SBQE9GHSS','Molycorp','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('67DOLO7DQTAJGNCI7NJ9MF1ECI','NYSE:LXFT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3G5JC2MQJCS2F9KPMLUJG6OAQO','NYSE:MOG.A','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('54PEMEG594M0738JIGPBINCO1H','NASDAQ:GAIN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1I3D9TG4KOA245QP5GDL0UMDPQ','NASDAQ:TISA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6BUVL8T18C1OR7T7HMQF70IGT1','NASDAQ:IACI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('27OUIMVC21VPJOSI1EFUSD7OGG','OTC:FTER','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5871QLIFQF4AVD86BO7T81NA98','NYSE:ET','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('66HM0B69UU2NH4R1UHUOGUKHKV','NYSE:STM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('62560SSVPOER60PGLMJE22P0KK','TSX-V:VZX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3PD6PF0LCT8ECFV57U8NHCKKHL','NASDAQ:CTXS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1T3B1NOBG7G47RHJ79926LFQ9G','ONEM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1SA2M30GKSVO05NJ7HT5TAN5F','NASDAQ:PETX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1IIQ3HJJ8CM3ILA3J9HSL3H0KH','NYSE:HAR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5NF6SN6LHC7Q2DKB824FRHJ3V1','NYSE:ECOM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2DDM8R2UBQLL9FJ3DM7KCNIMD6','VG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2B2TROEEGK17LGOF28GCHPBNUP','NYSE:TYC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5VD99O7V3PGTLOGQKAIGRER11O','NYSE:WWAV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1DLC7G78DS3NN1MI8EJ8FHPK1H','NYSE:CSTM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4BGDO07EK25LUGFJQSBTFSEF94','NASDAQ:CRTO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7GRSAM5AL56OP4PQK6OA6UB3AI','NYSE:ICE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5GV28D3G2772P8VE3HUB3SOK7','NYSE:HAE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3SU6KBM54TA6ASDS6LUKJLA6C9','NASDAQ:AVAV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4HB6PLF3IE3QPHVVFP1B6MURI0','LOOP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('237Q8TMQP4BG86D28QFN9S3725','NASDAQ:ZBRA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2SLCGRERL98900ERF8ADQV41US','OTC:ASTV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7KKG5A5IGCLRKB9KJH59PKKEFK','NASDAQ:ANSS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('3I86UHJERGJMGF8Q07NNK8LR95','9449','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3F71BA4DTRIF9V15158CPF61UD','NYSE:IBM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('32GDNK98C063N2CRVESJD48KSK','NYSE:AMPE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5N98N0MLKOBLB8FRFLR40O195P','NASDAQ:FURX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('JLDKC3PU1H675NBD4ALJHK225','NASDAQ:ICEL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6ECPLVSKBH8DNR1L4CAOOV346V','NYSE:CVT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7P9P6EACEC5RIUF63QA77PDJPG','JAZZ','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5M3MGMR7F155N870KCPMP6BRJD','WM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7ESIEH562Q77R7DP2VT4H9PFTK','NYSE:ARW','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2AISVHHVKPOF0EKO1MQN3FLN2P','NASDAQ:OLED','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('4N87MANMRJGM3NVUR8O78GDS95','NYSE:YOKU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7M4OF5SKF45A7LJ8QR68QPUBF3','NASDAQ:IBCP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5FA4L86MCHQIM7ET38BMU8A4OP','NYSE:AVG','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5AJ3PTDGDMU86NGQSNKHNGNOTJ','NYSE:SI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3JNDEA91FTH9P4UDB3ANBU7NR','SABA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4NE8485LK611KVQEULBH5M3MHU','NYSE:ST','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6E9TVBTJ2F24IGL4R7FPMI1DMB','NYSE:IEX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('75DKAP4NS6BQLNCFKNH4QMV9SP','OTCBB:NVIV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1VFH47T6F5UMODFF4DKI4J01BV','OMER','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('72C0G711C22CE3T039PO1RRAF9','NASDAQ:LDCL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('17FGQVMBFEB296SDAT07DBTPMT','OTC:AMCY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('51DIT1B2JP702PKQSPOLJITPFD','NASDAQ:AVGO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5MMQQH1OF9N0H414E4UFMSEQ6G','NASDAQ:GALT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7AEBHQN00TG0BD5D9J3AG0NNMF','SFLY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('HVFNJ4P5IMK1KMDNBPM0V2MQU','NYSE:BRSS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('62M0H1KA8VT5EH09MU5TVNECG0','NYSE:NOK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4EF5U0MHGH5U7VN73K4MKEN5FO','NASDAQ:ONNN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('VVTD4RMSGSUKEU2UH6E31QDV3','NASDAQ:ALTR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6RFJVS9N8IA4VTCT3HVJ207GJ2','NYSE:MMM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2SQMM6V4U4C7KPD7357RKDJCU1','NASDAQ: SPRD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('77UAFJE41A5HCSDLCTMFGRLG0S','NASDAQ:ACCL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('417NVMPTGFO3PLI3J3HM4M32LR','NASDAQ:XXIA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('231BSCB40SUKJQCAT7V8UP0FR9','NYSE:QTS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('312IUJ1I7NDAECCQ3D1U9RGONI','NASDAQ:MXIM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5JUR681EDJT0K9VAK8F9J7ECC2','NASDAQ:FEYE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3I154P81C9Q2FM6MDHGPQG4CCQ','CDXS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7E6EKPRLA3I5OK0N5HK1B93P67','NASDAQ:EMKR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('PC0CL7OLJ83F9JDKA6CE02GNV','PVS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5P3SG0OAVDIQEMM0JGNN0QFKUE','NYSE:OPK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6S62SL4M9F44RK5OGK4SBPBM1','MAHH.BO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('2JPFST2G00TV645G3KM67G6BKQ','NYSE:KKR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('712IMQH1M0J781TE4D29D92PTP','EPA:COX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('QQ7G18SUMRF4PC82UG5S5BKIC','LSE:SFT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3F757TCHKPM8V28M2K4T1N1B11','PDSN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3VPEHUF1TPUL1UCINS5P6IDMK8','OTC:PHOT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3D4V02KKNRE9P3L11BQAJ1JPPD','OTCBQ: MCVE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5MHMFKRCGVGL679DEJ8L69KD4K','GOCH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('25A7S2JDUAHR83N22I5JGBBOIU','NYSE:CALX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5HE7HQC963A7S8831K0GUK8GTH','NASDAQ:VLTC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1TQAC3V1NSMROLE81FSU0U4QM0','NASDAQ:ATAI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('455GJ3NJ8EOCJTN29GB6JGCS7T','NASDAQ:HEOP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6TEK9FBO18JJESSPLGV2UA1GK0','PROJ','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1KLGD2LJ8SUDVAQ2T9E2UC72J6','ASX:BLR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('57D4JC2P8H0FVJNPSN10MHDQLR','NASDAQ:ADBE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('22EIFG4OF58KMPCV81K84PJ0LP','NYSE:MON','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4K9GJBJBFH330SH8OR94D60M9F','NYSE:GCI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('32BT28BH8G1JR95V6PKGJKNJ66','NASDAQ:AGIO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('9MPI12NKPD3864FCCQLLPKPFH','NYSE:PTR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2P2VOKFNSQNHNQ7GDMT6QOD60R','NASDAQ:COST','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3ARRHL49ELSKNSMKOTL7E18J7G','NASDAQ:GOGO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('54GCOEFMUQELMI4F3KNOEMUNVS','NASDAQ:CNQR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('254POQL84HVL5EMQOMHIAFPP66','NASDAQ:GRMN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5B2N1RNG18G60AEELGEBUN819K','GWRI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3MC55E64CC9C81BN1AI1OHBIKK','NASDAQ:ISIL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3QUVH9Q2JKTNGRHTFS901LTVA5','NASDAQ:IPCI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('338QJILEK7M69RS4C6DM39MD32','NASDAQ:RMBS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5JGM7T5PUVV5DBG3H4QHBBCAG3','OTN:RYUN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6LBGUHGK743FT24071A7BT3SFV','NASDAQ:RCON','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6L5KPO7VDJKVPBJJVJE31GK3L4','NASDAQ:EZCH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7VECUNHM7T1AM2BJPFN9MPU008','NASDAQ:ISIS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('6PS2K7DD6BV2J35CQKUORP7UN1','NASDAQ:NWBO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1G3GR6LI21TRHE5KQ371ALJ1VV','NASDAQ:KIOR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7SPNCPVNAHFN27K9U5KNIOKI8H','NASDAQ: ETFC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4K5GQGTJKPC4HDLNDUP0SK3ETO','NASDAQ:EPOC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1T58MUK35724TR30E537NPHBNM','NYSE:INUV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6ISPBAAE02Q8Q47661J48GCHLM','NASDAQ:ACAD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4HQMFCC533BQRGL7DRN1CN2I5','NASDAQ:ZIP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('29BUOMDJ8T2E60JCHV5PCUDRS6','NASDAQ:XLNX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('77LR4Q5TLA569JUVI730QBG24Q','NYSE:NSPR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4FJIFV14HIUOVEAAOCQFENF8HE','GDOT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('68BAGHRI8KPKC9B8PAS6NK8C7D','NYSE:GEL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('GIOC6KUUDLIKAH85U052PNAVD','OTC:LBIO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5442QCEQVV9IKK44ILULBSAI9U','NASDAQ:FLIR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('51E74F8BLIDSQFD9RB8GV3J28U','NASDAQ:WBCO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('75NO900GNJJ0R5SHUUARU5CDPH','OPESF','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5LIBOIEUNEPE053NDO23BA02Q6','NASDAQ: HNSN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3TJMN0IL1GNFSMTC64PQJEFQR','NASDAQ:EWBC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('726D80BV7HMC6HFP9FMN4F1FUQ','NASDAQ:NTAP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4JK459QJ8106C2VA63P2NCE20E','OWW','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4CQIMBOGB6VQ2KH7R5V2FHSQI9','NASDAQ:AMZN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('65JTFU6RPC5P7HVDCCI16AA8UC','NASDAQ:ENPH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4KSC1IJ1BUNIG3RQI2IAKO0PBI','NASDAQ:ADHD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3VFJHUG17QJ8442DSR8VTNHCN3','NYSE:ACTV','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('70BF9N5EIN2ETUQSKR1BH4860M','NASDAQ:MCBI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('67NBI93I9QQM9FGNN57KR441UR','QPSA (AMEX)','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5OG3HNBDEFC57NP5QQU1RD5SKO','NASDAQ:CNVO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2S5L0HGU593GAQM83PS0JDGABR','NASDAQ:NDAQ','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1L9DN6IH5I7993QSB7J86J5GUQ','OTC:WANSF','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5MQ9E5TEV6POC9HIU76HOHJH9V','AVEO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3JIG7RG82BG0DS2PE17RQP4UA2','NASDAQ: BBND','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('1SNCJRS2LEO17MH2233LOHUIPP','NYSE:VJET','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6VR928JO4E1VCO4JCU7IQCOFCJ','NASDAQ:FPRX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1RVBAJ2FQJHN1BA7HN3JHSV874','NASDAQ:TRMB','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2TUEARUE2AA65GQEQO2JD4CT62','NYSE:B','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('40FVK6V0U1JC326AINGKFSULAR','NYSE:FBN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('69A7Q55ACPKV6AV32PTTJ9TAEH','NASDAQ:TLAB','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6886JDAAQ962P58UUAST5810EE','NYSE:A','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4HSVOVFRE1ELV6I2D91TBCU3GU','NYSE:IHS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3F23RBD7M96VFCUG8O9NUH2MGV','NASDAQ:MKTO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('321ML7H98E4QJL8AF8C78DN35P','NASDAQ :CNAT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('5FO5AQAHUD5VGNU8O1050RAE7S','NYSE:STAY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4CTJF84NGB46L9RUFDILR9MCR2','BLNX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3CU5QA23PE0838OMONI8FI3VHG','NYSE:LNKD','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2ILBINDFQOJKIGA3BNO58KSG81','FFN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4ESM43OBKJ8FT1JI0HMMMQEP5H','OTC:RHHBY','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1AMEHKKTQIIVGPOB23MA6UMMHQ','NYSE:F','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5LU6TBSG9H7JH1TBT77SSJVBAP','NYSE:T','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2ORVQPENA0IVOUGLVRG2R73QH7','NASDAQ:TNDM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7AV5U9UB9JKRKFG5N7F1EBM09N','NYSE:P','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('609EDRMF8527K3299APVRNTFE4','NYSE:Q','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('3I5N1RPTG1FSIFBP7EUI8OM02G','NYSE:N','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('51GFJJUFO4MN7A0EJIH58FJVHC','NASDAQ:LRCX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1O7AV9UH57OVRNU3RU0HRRM1V7','NYSE:JNPR','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('78O75ADC8EMROF4DVB975VNCRR','NASDAQ:EIGI','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5F87CLG9G1BHHJ6T09L0H5T5RB','NASDAQ:WIX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5VNGKFGGUQEQKLK4QOTJ6LA08R','NASDAQ:GOMO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1ONNFOIAGVTNJ7IVO77AQ59JF3','NASDAQ:MSCC','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6C0AGQCTU4MNTI6MCMG2RB6IQK','Nasdaq:CBRX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('351F3EEIS01RH0LTF43QKT7BF9','NASDAQ:CHKP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6MCP671RCSEGGDJC4PVMJPRDHI','NYSE:V','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('9C66LG22GBEJFJEKHBQ25DC1A','OTC:ADMA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('UM995QS82I6Q46DLOID5VO2J0','NASDAQ:TSLA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('310P03FJ5K7MA87U8HLTTBCJEP','OTC:ECAU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1CDEQFUQQ3LM9VM9M2H55H9BI3','LEDS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1D8QJLFR8T5MBUO3QQFK9PNSDR','NYSE:HIT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2GHITBCQL8MJCE1V9TG81VD1A','NASDAQ:JIVE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6MUQE9B0K61SP2GHA5Q7MQADPQ','NYSE AMEX: YMI; TSX:YM','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2TD3QP7AO8QS59ASOD4POG8Q00','ASX:MEP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4FE70UQPTB69E7LCVDTC8BT8PV','NASDAQ:NUAN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4EH8LDPL1F9Q7RKGAO2FJ5AK78','TYO:3681','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('7S7PADCF6K2C4SLD24LCJE0SAL','RSOF','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1U9HFPVBQ2GLHHNB4FMH44L485','NASDAQ:PATH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('30RLAES4NM83809246OMNOSSLT','NASDAQ:SPHS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4IAUSBP44DNDT08C8HKAI5SFIO','TYO:4776','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4UK7I17MHGVFA3JC2N0R5U8QN','RVUE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('59SNAKHM1T0KV0SV0ACPTLTFEO','CMNN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('U38I7LGJERK3KAMGNLIO6UKCU','NYSE:PT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('KPK1BACIGBS7M0NM4KK4JDFV6','NASDAQ:GRPN','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('3Q5AT1C0FFNAIQ8DLQ172E4N1T','RSOL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4LDILM4TKN01953LRB233DVOS4','NASDAQ:LBAS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('KMTV631EF5GEBBP6QPG9KU28S','NASDAQ:SNDK','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2DOAKRR060Q0BU87NT876F4HE1','SODA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6TNU2VIV67MF162GM7A4FP3GJS','NASDAQ:IPGP','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4HGA2MMTO6J8LH6QAK29H2O38I','NYSE:NTT','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('6PAGGBOH3BGU5ERGB6N74CS6RC','NASDAQ: ASTX','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('4NGLE5HHQM61KC21JE9IRQI5C','NASDAQ:SRNE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5GMRU81K81U2GIP73ONDRAQ5J0','TCS','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7QU0SSEGAN1FAD5L5S8H5MQFO9','NASDAQ:MU','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1DND11RS27QI2KIV18GQ1A805','NASDAQ:IRKO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('2OQOL1EP4E3SHEH9FOQ0RL3D7Q','GOFH','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;
INSERT INTO mart_exchange.hub_exchange (exchange_hash_key,exchange_code,record_source) VALUES 
('4GE7V70C7T25L5GPEVMLA4QPKI','NASDAQ:BLUE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('7TBSK19S9TSTPEHKRKML8071AN','NASDAQ:ARCL','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('5ASP6DKDDDLC8308LP0L4R9075','NASDAQ:SALE','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('72I2PFKAHRRKUF0EDCBEOLI2S6','NYSE:GIMO','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('1AUCU0LQ5D2VDD19N9BK3H9OHQ','NASDAQ:HFWA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
,('73NJV2UL20ACVCCQPMOV07JQ5H','NASDAQ:NVDA','C:UsersстепанPycharmProjectskdz2_dmipos.csv')
;